<style type="text/css">
/* Whole document: */
body{
  font-family: "Palatino Linotype", "Book Antiqua", Palatino, serif;
  font-size: 12pt;
}
h1.title {
  font-size: 38px;
  text-align: center;
}
h4.author {
  font-size: 18px;
  text-align: center;
}
h4.date {
  font-size: 18px;
  text-align: center;
}
</style>

---
title: "Lab 1"
author: "STAT 302"
date: "1/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Instructions (5 points)

This lab will be worth 20 points, of which 5 can be earned by following instructions. Each item below is worth 1 point.

* You must upload this file as a compressed file (such as `.zip`) of your *entire* STAT302 folder. The organization and file names should follow the guidelines outlined in the Lecture Slides 1. This means that the actual .Rmd and .html files for Lab 1 should be included in a Lab 1 subfolder within a Labs folder.
* Your code should be commented so that it is easy for us to follow.
* Your code should follow the style guidelines from Lecture Slides 1.
* Any reference to code results in text should be done using in-line R code. You should not be typing the actual numbers. Similarly, any values you are asked to calculate must be done using code. They should not be calculated by hand.
* Your document should look nice and be easy to read. Figures should be appropriately sized, headers and subheaders should be used, etc.

When generating data, I recommend viewing and exploring your data to get a sense of what it looks like using both R commands and the Editor tab in RStudio. 
This will help you confirm that what you generated is what you intended. 
It will also give you a sense of what the data look like, which can help decide how you want to present it.

*If you collaborated with anyone, you must include "Collaborated with: FIRSTNAME LASTNAME" at the top of your lab!*

## Part 1. Vectors (8 points)

Let's jump right in and start working with large simulations. You will need the functions `rnorm()` for Normally distributed simulations, `pnorm()` for the percentiles of the Normal distribution, and `dnorm()` for the density of the Normal distribution. This is all I am going to tell you about these functions, so you will need to use the documentation to help you with these questions! (*Hint: pay attention to the parameter* `lower.tail`)

**1a.** Create and store a vector of 100,000 simulations from a Normal distribution with mean 7 and standard deviation 3 (sometimes shorthanded $N(7, 3)$). Print out only the first 5 elements of your vector using `head()`.

**1b.** Generate 5 histograms. The histograms should include the first 10, 100, 1000, 10000, and 100000 elements of your simulations, respectively. Be sure to change the title of your histograms to write what they display in plain text. (*Hint: use the parameter* `main`) What do you notice about the histograms? Explain why you think this is.

**1c.** In order to standardize vectors, we take each element and subtract the mean and then divide by the standard deviation. Create and store a new vector that is the standardization of your simulations from part (a). Create a histogram for these standardized simulations (don't forget to change the title again!). What do you notice? Include references to the mean and standard deviation of your new data, using in-line R code.

**1d.** Calculate (using an R function) the percent of simulations from a $N(0, 1)$ that you *expect* to be above 1.644854. How does this compare to the observed proportion of your standardized simulations that are above 1.644854?

**1e.** How does the quantity from part d compare to to the observed proportion of your first 10 standardized simulations that are above 1.644854? Repeat this for your first 100, 1000, and 10,000 standardized simulations. 
What do you notice?

**1f.** I simulated from an unknown distribution and obtained a value of 13.86. What is the percentile of my simulution in the distribution of your simulations? If you standardize my simulation (using the same mean and standard deviation as in part c!), what is the percentile of my simulation in the distribution of your standardized simulations? What do you notice about these two quantities?

**1g.** What percent of simulations from a $N(0, 1)$ would you *expect* to be more "extreme" than my standardized simulation? Here, "extreme" means further from the mean in either direction.

**1h.** Do you think it is likely that my simulation was drawn from the same distribution as your simulations? Why or why not?

## Part 2. Matrices (7 points)

A Binomial distribution with $n$ trials and probability of success $p$, sometimes shorthanded $Bin(n, p)$, represents the number of success out of $n$ independent trials, each with probability of success $p$. 
For this part, we will be using the Binomial distribution equivalent of the functions we used in part 1.
These are `rbinom()`, `pbinom()`, and `dbinom()`.

**2a.** Initialize two empty matrices. One should have 100 rows and 4 columns, the other should have 100,000 rows and 4 columns. Be sure to give them informative names that follow style guidelines.

**2b.** Separately fill the first column of each matrix with draws from a Binomial distribution with probability $0.2$ and $n=5$. Repeat this process for the second through fourth columns using probabilities of $0.4$, $0.6$, and $0.8$, respectively. Print out the first five rows of each matrix.

**2c.** Use four well-labeled histograms to plot the values of each column. Set the `breaks` parameter to a reasonable value for these data. Discuss what you see.

**2d.** Calculate the column means of both matrices and present these results in a single table. The rows and columns of your tables should be easy to read and interpret.

**2e.** What is the *expected* column mean for each column? Which matrix has observed column means that are closer to this expectation? Why do you think that is?

**2f.** Repeat parts b through e but now use $n=1000$. Discuss the differences and similarities.

**2g.** With your new simulations from part f, present the 5-number summary of each column in both matrices in a single table. Be sure to label the rows and columns of the table. Which matrix has more "extreme" maxs and mins? Explain why you think this is. (*Hint: Use the function* `summary`. *There are many ways you can present this table. Personally, my table would have 8 rows and 5 columns.*)

